<style>

body {
  font-family: "Georgia";
  text-align: justify;
}

p {
  font-family: "Georgia";
  text-indent: 30px;
  color: black;
  font-style: normal;
}
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Homework week 4

## Slide 99

1. Compute $\,dW_t^2$ in terms of $\,dt$ and $\,dW_t$.
2. Compute $\,d(\sin W_t)$ in terms of $\,dt$ and $\,dW_t$.
3. Let $\,d X_t =5 \,dt+3 \,dW_t$. Compute $\,d(\sin X_t)$ in terms of $\,dt$ and $\,dW_t$.
4. Let $\,d X_t =5 \,dt+3 \,dW_t$. Compute $\,d(X_t^2)$ in terms of $\,dt$ and $\,dW_t$.
5. Let $\,d X_t =5 \,dt+3 \,dW_t$. Compute $\,d(e^{X_t})$ in terms of dt and dWt.
6. Let $\,d X_t =5 X_t \,dt+3 X_t \,dW_t$. Compute $\,d(X_t^2)$ in terms of $\,dt$ and $\,dW_t$.
7. Let $\,d X_t =5 X_t \,dt+3 X_t \,dW_t$. Compute $\,d(\sin X_t)$ in terms of $\,dt$ and $\,dW_t$.
8. Let $\,d X_t =5 X_t \,dt+3 X_t \,dW_t$. Compute $\,d(e^{X_t})$ in terms of dt and dWt.
9. Let $\,d X_t =5 X_t \,dt+3 X_t \,dW_t$. Compute $\,d( \log {X_t})$ in terms of dt and dWt.
10. Let $\,d X_t = 5(4 − X_t) \,dt + 3X_t \,dW_t$. Compute $\,d(e^{5t}X_t)$ in terms of dt and dWt.

## Slide 100

1. Find the second-order Taylor series expansion of $f(x)=e^{x+y}$ 
2. Find the second-order Taylor series expansion of $f(x) = \sin(xy)$
3. Find the second-order Taylor series expansion of $f(x)=\ln \left( \frac{x}{y} \right),x,y >0$

## Slide 104

Let $(W_t)_{t \geq 0}$ be a Brownian motion on the filtered probability space $(\Omega,\mathcal{F},(\mathcal{F}_t)_{t \geq 0},\mathcal{P})$. Compute $\,dX_t$ in terms of $\,dW_t$ and $\,dt$, where:

1. $X_t=10e^{0.5 \left(0.1-\frac{0.3^2}{6} \right)t+\frac{0.3}{\sqrt{3} W_t}}$.
2. $X_t=Y_t^3$, with $\,d Y_t=2Y_t\,dt+3Y_t\,dW_t$.
3. $X_t=\log Y_t$, with $\,dY_t=4tY_t\,dt+2tY_t\,dW_t$.
4. $X_t=\frac{4-Y_t}{1-t}$, with $\,dY_t=X_t\,dt+\,dW_t$.

## Slide 106

1. $ty′(t)+2y(t)=4t^2,y(1)=2$.
2. $2y′(t)+ty(t)=2,y(0)=1$.
3. $y′(t)−y(t)=2te^{2t},y(0)=1$.
4. $y′+y^2 \sin x=0,y(2)=1$.
5. $y′ =(1−2x)y^2,y(0)=1$.
6. $x \,dx+ye^{−x}\,dy=0,y(0)=1$
7. $y'(x)=\frac{x^2+xy+y^2}{x^2},y(2)=2$.
8. $y'(x)=\frac{x^2+3y^2}{2xy},y(2)=2$.

## Slide 118

Let $\{(W_t)_t \geq 0\}$ be a standard Brownian motion on the probability space $(\Omega,\mathcal{F},\mathcal{P})$. Suppose that the process $(X_t)_t \geq 0$ is governed by the geometric Brownian motion:
$\,d X_t = 8X_t\,dt + 2X_t\,dW_t$.
Find the distribution, the mean and variance of the random variable $(X_5|X_3 = 4)$.

## Slide 122

Let $\{(W_t)_t \geq 0\}$ be a standard Brownian motion on the probability space $(\Omega,\mathcal{F},\mathcal{P})$. Suppose that the process $(X_t)_t \geq 0$ is governed by the geometric Brownian motion:
$\,d X_t =4(t^3−3)X_t\,dt+t^2X_t\,dW_t$.
Find the distribution, the mean and variance of the random variable
$(X_4|X_2 = 3)$.
